# Vectors Chapter 1

In [4]:
import numpy as np

# Vector representation
mereList = [1, 2, 3]
asArray = np.array([1, 2, 3])  # !D array
rowVector = np.array([[1, 2, 3]])  # Row vector
columnVector = np.array([[1], [2], [3]])  # column vector
threeVector = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(threeVector.shape)
print(f'asList:  {np.shape(mereList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec:  {rowVector.shape}')
print(f'colVec:  {columnVector.shape}')

(3, 3)
asList:  (3,)
asArray: (3,)
rowVec:  (1, 3)
colVec:  (3, 1)


In [7]:
v = np.array([[4], [5], [6]])
w = np.array([10, 20, 30])
u = np.array([0, 3, 6, 9])

print(v + w)  # Broadcasting
print(v + u)

[[14 24 34]
 [15 25 35]
 [16 26 36]]
[[ 4  7 10 13]
 [ 5  8 11 14]
 [ 6  9 12 15]]


Broadcasting is a common concept in vector addition and python

In [8]:
# Scalar Multiplication
s = 2
a = [3, 4, 5]  # as list
b = np.array(a)  # as np array print(a*s)
print(b * s)

[ 6  8 10]


## Vector Magnitude
The magnitude of a vector—also called the geometric length or the norm—
is the distance from tail to head of a vector

In [10]:
v = np.array([1, 2, 3, 4, 5])
v_dim = len(v)  #no. of elements
v_mag = np.linalg.norm(v)
print(v)
print(v_dim)
print(v_mag)

[1 2 3 4 5]
5
7.416198487095663


## Dot product
computational building block from which many operations and algorithms
are built, including convolution, correlation, the Fourier transform, matrix
multiplication, linear feature extraction, signal filtering, and so on.

In [11]:
v = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])
np.dot(v, w)

70

## Linear weighted combination

In [13]:
l1 = 1
l2 = 2
l3 = -3
v1 = np.array([4, 5, 1])
v2 = np.array([-4, 0, -4])
v3 = np.array([1, 3, 2])
l1 * v1 + l2 * v2 + l3 * v3


array([ -7,  -4, -13])